/// Flutter icons HousePartyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HousePartyIcons
///      fonts:
///       - asset: fonts/HousePartyIcons.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class HousePartyIcons {
  HousePartyIcons._();

  static const _kFontFam = 'HousePartyIcons';
  static const _kFontPkg = null;

  static const IconData pencil = IconData(0xf330, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out = IconData(0xf339, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_in = IconData(0xf365, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
